version: "3.9"  
services:

  local-currency-db:
    deploy:
      restart_policy:
        condition: always
    image: mongo
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  local-currency-api:
    deploy:
      restart_policy:
        condition: always
    x-aws-policies:
    - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
    depends_on: 
      - local-currency-db
    image: aaronmboyd/local-currency-core:api
    x-aws-pull_credentials: "arn:aws:secretsmanager:eu-north-1:741204600220:secret:dockerhubAccessToken-FuYCes"
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
      # x-aws-protocol: http
    environment:
      DEBUG: "true"
      NODE_ENV: development
      REGION: eu-north-1
      SECRET_NAME: LOCAL_CURRENCY_API_ALFAJORES

      # Keep these here as a backstop for when using NODE_ENV: development
      LOCAL_CURRENCY_RPC_HOST: "https://alfajores-forno.celo-testnet.org/"
      LOCAL_CURRENCY_ADDRESS: "0xa493032Db59AcbcBF148F5C3660786ef8c6caa42"
      LOCAL_CURRENCY_MNEMONIC: "truth half motor knee sad flee oxygen gossip announce train soon renew"
      DERIVATION_PATH: "m/44'/52752'/0'"
      NUMBER_OPERATORS: 2
      DWOLLA_BASE_URL: "https://api-sandbox.dwolla.com/"
      DWOLLA_APP_KEY: r25yOHtHXrmojK2XBnTUXSFjxzT1fQpmOdEAu3eo50CNqHjwDW
      DWOLLA_APP_SECRET: uYWA0wHz5pf8Is26RfSvnZgEX5Rhyjyiq2yIxYka7m4T7xSZIl
      DWOLLA_ENVIRONMENT: sandbox
      WEBHOOK_SECRET: 0000000000000000000000000000000000000000000001
      MONGO_URL: "mongodb://root:example@local-currency-db:27017"

  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - local-currency-api

volumes:
  db_data: