version: "3.9"  
services:

  local-currency-db:
    image: mongo
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  celo-node:
    image: us.gcr.io/celo-org/geth:alfajores
    restart: unless-stopped
    volumes:
      - celo_data:/root/.celo
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    command: ["--verbosity", "3", "--syncmode", "full", "--rpc", "--rpcaddr", "0.0.0.0", "--rpcapi", "eth,net,web3,debug,admin,personal", "--light.serve", "0", "--light.maxpeers", "1000", "--maxpeers", "1100", "--nousb", "--alfajores", "--datadir", "/root/.celo"]

  local-currency-api:
    x-aws-policies:
    - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
    depends_on: 
      - local-currency-db
    image: local-currency-core:api
    x-aws-pull_credentials: "arn:aws:secretsmanager:eu-north-1:741204600220:secret:dockerhubAccessToken-FuYCes"
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
      # x-aws-protocol: http
    environment:
      DEBUG: "true"
      NODE_ENV: development
      REGION: eu-north-1
      SECRET_NAME: LOCAL_CURRENCY_API_ALFAJORES

      # Keep these here as a backstop for when using NODE_ENV: development
      LOCAL_CURRENCY_RPC_HOST: "https://alfajores-forno.celo-testnet.org/"
      LOCAL_CURRENCY_ADDRESS: "0xa493032Db59AcbcBF148F5C3660786ef8c6caa42"
      LOCAL_CURRENCY_MNEMONIC: "truth half motor knee sad flee oxygen gossip announce train soon renew"
      DERIVATION_PATH: "m/44'/52752'/0'"
      NUMBER_OPERATORS: 2
      DWOLLA_BASE_URL: "https://api-sandbox.dwolla.com/"
      DWOLLA_APP_KEY: r25yOHtHXrmojK2XBnTUXSFjxzT1fQpmOdEAu3eo50CNqHjwDW
      DWOLLA_APP_SECRET: uYWA0wHz5pf8Is26RfSvnZgEX5Rhyjyiq2yIxYka7m4T7xSZIl
      DWOLLA_ENVIRONMENT: sandbox
      WEBHOOK_SECRET: 0000000000000000000000000000000000000000000001
      WEBHOOK_URL: "https://alfajores.api.humanity.cash/webhook"
      MONGO_URL: "mongodb://root:example@local-currency-db:27017"
      VIRTUAL_HOST: alfajores.api.humanity.cash
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: alfajores.api.humanity.cash

  nginx-proxy:
    depends_on:
      - local-currency-api
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html

  letsencrypt-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    container_name: letsencrypt-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=tech@humanity.cash
      - NGINX_PROXY_CONTAINER=nginx-proxy
networks:
  default:
    external:
      name: nginx-proxy
volumes:
  db_data:
  celo_data:
  letsencrypt-certs:
  letsencrypt-vhost-d:
  letsencrypt-html:
