version: "3.9"  
services:

  local-currency-db:
    image: mongo
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  local-currency-api:
    depends_on:
      - local-currency-db
    build: ./
    image: local-currency-core:api
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
    environment:
      DEBUG: "true"
      NODE_ENV: development
      PORT: 3000
      LOCAL_CURRENCY_RPC_HOST: "https://celo-alfajores--rpc.datahub.figment.io/apikey/25daa59318b13c1f83a8a444578fdb57/"
      LOCAL_CURRENCY_ADDRESS: "0xa493032Db59AcbcBF148F5C3660786ef8c6caa42"
      LOCAL_CURRENCY_MNEMONIC: "truth half motor knee sad flee oxygen gossip announce train soon renew"
      DERIVATION_PATH: "m/44'/52752'/0'"
      NUMBER_OPERATORS: 2
      DWOLLA_BASE_URL: "https://api-sandbox.dwolla.com/"
      DWOLLA_APP_KEY: r25yOHtHXrmojK2XBnTUXSFjxzT1fQpmOdEAu3eo50CNqHjwDW
      DWOLLA_APP_SECRET: uYWA0wHz5pf8Is26RfSvnZgEX5Rhyjyiq2yIxYka7m4T7xSZIl
      DWOLLA_ENVIRONMENT: sandbox
      WEBHOOK_SECRET: 0000000000000000000000000000000000000000000002
      # WEBHOOK_URL: "https://alfajores2.api.humanity.cash/webhook"
      REGISTER_WEBHOOK: "false"
      SIMULATE_WEBHOOK: "true"
      PORT: 3000
      SIMULATE_BANKING: "false"
      USE_MANAGED_SECRETS: "false"
      OPERATOR_1_FUNDING_SOURCE: "https://api-sandbox.dwolla.com/funding-sources/7fe7a621-e494-4369-965f-214477122331"
      OPERATOR_2_FUNDING_SOURCE: "https://api-sandbox.dwolla.com/funding-sources/2bbb3d39-1e43-4c34-8e00-a96b286f3bab"      
      MONGO_URL: "mongodb://root:example@local-currency-db:27017"

volumes:
  db_data:
