name: Build

on: [ push, pull_request ]

jobs:
  build-api:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Pre-install
        run: |
          cd api
          yarn install --check-files --cache-folder .ycache
          npx ganache-cli -m "recall exit lawsuit early about crack empower execute outdoor artefact harbor cover" &
          rm -rf .ycache
      - name: Run Checks
        run: |
          cd api
          yarn prettier
          yarn eslint
      - name: Run build
        run: |
          cd api
          yarn build
      - name: Run tests
        run: |
          cd api
          touch .env
          yarn coverage
        env:
          DEBUG: "false"
          NODE_ENV: "test"
          PORT: 3000
          LOCAL_CURRENCY_PROVIDER: "web3"
          LOCAL_CURRENCY_RPC_HOST: "http://localhost:8545"
          LOCAL_CURRENCY_ADDRESS: ""
          LOCAL_CURRENCY_MNEMONIC: "recall exit lawsuit early about crack empower execute outdoor artefact harbor cover"
          LOCAL_CURRENCY_MNEMONIC_INDEX: 0
          NUMBER_OPERATORS: 2
          OPERATOR_1_DWOLLA_USER_ID: "608b7adc-4c73-46f7-88ee-85095e2c63f1"
          OPERATOR_1_MNEMONIC: "recall exit lawsuit early about crack empower execute outdoor artefact harbor cover"
          OPERATOR_1_MNEMONIC_INDEX: 0
          OPERATOR_1_DISPLAY_NAME: "Lee Bank"
          OPERATOR_2_DWOLLA_USER_ID: "a5426c13-a2f0-4812-b7be-3fc9b5a70de3"
          OPERATOR_2_MNEMONIC: "recall exit lawsuit early about crack empower execute outdoor artefact harbor cover"
          OPERATOR_2_MNEMONIC_INDEX: 0
          OPERATOR_2_DISPLAY_NAME: "Salisbury Bank"
          DERIVATION_PATH: "m/44'/60'/0'"
          CUSTOMER_WITHDRAWAL_BALANCE_LIMIT: 5
          DWOLLA_BASE_URL: "https://api-sandbox.dwolla.com/"
          DWOLLA_APP_KEY: r25yOHtHXrmojK2XBnTUXSFjxzT1fQpmOdEAu3eo50CNqHjwDW
          DWOLLA_APP_SECRET: uYWA0wHz5pf8Is26RfSvnZgEX5Rhyjyiq2yIxYka7m4T7xSZIl
          DWOLLA_ENVIRONMENT: sandbox
          WEBHOOK_SECRET: 0000000000000000000000000000000000000000000099
          REGISTER_WEBHOOK: "false"
          SIMULATE_WEBHOOK: "false"
          SIMULATE_BANKING: "false"
          USE_MANAGED_SECRETS: "false"
          USE_MONGO_TLS: "false"
          TRANSFER_RECONCILE_ON_STARTUP: "false"
          CUSTOMER_DEFAULT_AVATAR_URL: ""
          BUSINESS_DEFAULT_AVATAR_URL: ""
          IMGIX_PROFILE_PICTURE_URL: "https://profile-picture-user.imgix.net/"
      - name: Run check git
        run: |
          git diff --quiet --exit-code --cached
