name: Build

on: [ pull_request ]

jobs:
  build-api:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Pre-install
        run: |
          cd api
          yarn install --check-files --cache-folder .ycache
          npx ganache-cli -m "recall exit lawsuit early about crack empower execute outdoor artefact harbor cover" &
          rm -rf .ycache
      - name: Run Checks
        run: |
          cd api
          yarn prettier
          yarn eslint
      - name: Run build
        run: |
          cd api
          yarn build
      - name: Run tests
        run: |
          cd api
          touch .env
          yarn coverage
        env:
          - CELO_UBI_RPC_HOST="http://localhost:8545"
          - CELO_UBI_MNEMONIC="recall exit lawsuit early about crack empower execute outdoor artefact harbor cover"
      - name: Run check git
        run: |
          git diff --quiet --exit-code --cached
